'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

interface SchedulerStatus {
  isRunning: boolean;
  nextRun: string | null;
  interval: string;
}

interface BlogPost {
  id: string;
  title: string;
  category: string;
  readTime: string;
  generatedAt: string;
  isAutoGenerated: boolean;
}

export default function AutoBlogAdmin() {
  const [status, setStatus] = useState<SchedulerStatus | null>(null);
  const [recentPosts, setRecentPosts] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState<'success' | 'error'>('success');

  // 获取状态
  const fetchStatus = async () => {
    try {
      const response = await fetch('/api/auto-blog/scheduler');
      const data = await response.json();
      
      if (response.ok) {
        setStatus(data.scheduler);
        setRecentPosts(data.recentPosts || []);
      } else {
        setMessage('获取状态失败');
        setMessageType('error');
      }
    } catch (error) {
      setMessage('网络错误');
      setMessageType('error');
    }
  };

  // 控制定时器
  const controlScheduler = async (action: string) => {
    setLoading(true);
    setMessage('');
    
    try {
      const response = await fetch('/api/auto-blog/scheduler', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ action }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        setMessage(data.message);
        setMessageType('success');
        // 等待一秒后刷新状态
        setTimeout(fetchStatus, 1000);
      } else {
        setMessage(data.error || '操作失败');
        setMessageType('error');
      }
    } catch (error) {
      setMessage('网络错误');
      setMessageType('error');
    } finally {
      setLoading(false);
    }
  };

  // 手动生成博客
  const generateBlog = async () => {
    setLoading(true);
    setMessage('');
    
    try {
      const response = await fetch('/api/auto-blog/scheduler', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ action: 'generate' }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        setMessage('博客生成成功！');
        setMessageType('success');
        setTimeout(fetchStatus, 1000);
      } else {
        setMessage(data.error || '生成失败');
        setMessageType('error');
      }
    } catch (error) {
      setMessage('网络错误');
      setMessageType('error');
    } finally {
      setLoading(false);
    }
  };

  // 初始化
  useEffect(() => {
    fetchStatus();
    
    // 每30秒刷新一次状态
    const interval = setInterval(fetchStatus, 30000);
    
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* 导航栏 */}
      <nav className="bg-white shadow-sm">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link href="/" className="flex items-center space-x-2">
            <span className="text-xl font-bold text-blue-600">NewWebAI</span>
          </Link>
          <div className="hidden md:flex space-x-6">
            <Link href="/blog" className="text-blue-600 font-medium">博客</Link>
            <Link href="/store" className="text-black hover:text-blue-600">产品</Link>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="bg-white rounded-xl shadow-md p-8">
          <h1 className="text-3xl font-bold text-black mb-8">自动博客生成管理</h1>

          {/* 状态显示 */}
          {status && (
            <div className="mb-8 p-6 bg-gray-50 rounded-lg">
              <h2 className="text-xl font-semibold text-black mb-4">定时器状态</h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <span className="text-sm text-gray-600">运行状态</span>
                  <p className={`text-lg font-medium ${status.isRunning ? 'text-green-600' : 'text-red-600'}`}>
                    {status.isRunning ? '✅ 运行中' : '⏹️ 已停止'}
                  </p>
                </div>
                <div>
                  <span className="text-sm text-gray-600">执行间隔</span>
                  <p className="text-lg font-medium text-black">{status.interval}</p>
                </div>
                <div>
                  <span className="text-sm text-gray-600">下次执行</span>
                  <p className="text-lg font-medium text-black">
                    {status.nextRun ? new Date(status.nextRun).toLocaleString('zh-CN') : '未安排'}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* 控制按钮 */}
          <div className="mb-8">
            <h2 className="text-xl font-semibold text-black mb-4">控制面板</h2>
            <div className="flex flex-wrap gap-4">
              {!status?.isRunning ? (
                <button
                  onClick={() => controlScheduler('start')}
                  disabled={loading}
                  className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
                >
                  {loading ? '启动中...' : '启动定时器'}
                </button>
              ) : (
                <button
                  onClick={() => controlScheduler('stop')}
                  disabled={loading}
                  className="bg-red-600 text-white px-6 py-3 rounded-lg hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
                >
                  {loading ? '停止中...' : '停止定时器'}
                </button>
              )}
              
              <button
                onClick={() => controlScheduler('restart')}
                disabled={loading}
                className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
              >
                {loading ? '重启中...' : '重启定时器'}
              </button>
              
              <button
                onClick={generateBlog}
                disabled={loading}
                className="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
              >
                {loading ? '生成中...' : '手动生成博客'}
              </button>
            </div>
          </div>

          {/* 消息显示 */}
          {message && (
            <div className={`mb-8 p-4 rounded-lg ${
              messageType === 'success' ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-800'
            }`}>
              {message}
            </div>
          )}

          {/* 最近生成的博客 */}
          <div>
            <h2 className="text-xl font-semibold text-black mb-4">最近生成的博客</h2>
            {recentPosts.length === 0 ? (
              <div className="text-center py-8 text-gray-500">
                暂无自动生成的博客
              </div>
            ) : (
              <div className="space-y-4">
                {recentPosts.map((post) => (
                  <div key={post.id} className="border border-gray-200 rounded-lg p-4 hover:bg-gray-50 transition">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="text-lg font-medium text-black">{post.title}</h3>
                      <span className="text-sm text-blue-600 bg-blue-50 px-2 py-1 rounded">
                        {post.category}
                      </span>
                    </div>
                    <div className="flex items-center text-sm text-gray-600 space-x-4">
                      <span>{post.readTime}</span>
                      <span>•</span>
                      <span>生成时间: {new Date(post.generatedAt).toLocaleString('zh-CN')}</span>
                      <span>•</span>
                      <span className="text-green-600">
                        {post.isAutoGenerated ? '自动生成' : '手动创建'}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* 说明信息 */}
          <div className="mt-8 p-6 bg-blue-50 rounded-lg">
            <h3 className="text-lg font-semibold text-black mb-2">使用说明</h3>
            <ul className="text-black space-y-1 text-sm">
              <li>• 定时器启动后，每小时自动生成一篇博客</li>
              <li>• 博客内容使用AI对话API生成，主题随机选择</li>
              <li>• 生成的博客会自动保存到LeanCloud数据库</li>
              <li>• 可以随时启动、停止或重启定时器</li>
              <li>• 支持手动生成博客进行测试</li>
              <li>• 定时器在服务器重启后会停止，需要手动重启</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}